"""
Financial Configuration Constants for DCF Valuation
"""

# Risk-Free Rate (10-year Treasury)
RISK_FREE_RATE = 0.045  # 4.5%

# Market Risk Premium
MARKET_RISK_PREMIUM = 0.04  # 4.0% (reduced for large-cap tech)

# Cost of Debt
COST_OF_DEBT = 0.04  # 4.0% (approximate corporate bond rate)

# Tax Rate
CORPORATE_TAX_RATE = 0.21  # 21% (US corporate tax rate)

# Terminal Growth Rate
DEFAULT_TERMINAL_GROWTH_RATE = 0.025

# WACC Bounds
MIN_WACC = 0.05  # 5%
MAX_WACC = 0.15  # 15%

# Default WACC (fallback)
DEFAULT_WACC = 0.10  # 10%

# Growth Rate Bounds
MIN_HISTORICAL_GROWTH = -0.20  # -20%
MAX_HISTORICAL_GROWTH = 0.50   # 50%
DEFAULT_MIN_GROWTH = 0.05      # 5% (default minimum growth rate)

# Minimum Growth Rates for Projections
MIN_STARTING_GROWTH = -0.10  # -10%
MAX_STARTING_GROWTH = 0.15   # 15%
MIN_BASELINE_GROWTH = 0.03   # 3%
FALLBACK_BASELINE_GROWTH = 0.05  # 5%
MIN_PROJECTED_GROWTH = 0.02  # 2%

# Growth Decline Factors
GROWTH_DECLINE_FACTOR = 0.90  # Growth declines by 10% per year

# Default Beta
DEFAULT_BETA = 1.0

# Conservative Valuation Factor
DEFAULT_CONSERVATIVE_FACTOR = 0.90  # 90%

# Default Forecast Years
DEFAULT_FORECAST_YEARS = 5

# Default Historical Growth Base Rate
DEFAULT_HISTORICAL_BASE_RATE = 0.07  # 7%

# Projection Method Options
PROJECTION_METHODS = ['declining', 'constant', 'cagr']

# Historical Years to Analyze
DEFAULT_HISTORICAL_YEARS = 5
FCF_HISTORICAL_WINDOW = 4  # Last 4 years for estimation

# Risk Evaluation Defaults
RISK_LOOKBACK_YEARS = 5
RISK_CACHE_DAYS = 7
RISK_VAR_ALPHA = 0.05

# Risk Thresholds (low/high) for scoring
RISK_VOLATILITY_LOW = 0.20
RISK_VOLATILITY_HIGH = 0.60
RISK_DOWNSIDE_DEV_LOW = 0.15
RISK_DOWNSIDE_DEV_HIGH = 0.50
RISK_VAR_LOW = 0.02
RISK_VAR_HIGH = 0.10
RISK_CVAR_LOW = 0.03
RISK_CVAR_HIGH = 0.15
RISK_BETA_LOW = 0.80
RISK_BETA_HIGH = 1.60
RISK_MAX_DRAWDOWN_LOW = 0.20
RISK_MAX_DRAWDOWN_HIGH = 0.60
RISK_DRAWDOWN_DAYS_LOW = 60
RISK_DRAWDOWN_DAYS_HIGH = 252

RISK_DEBT_EQUITY_LOW = 0.50
RISK_DEBT_EQUITY_HIGH = 2.00
RISK_NET_DEBT_EBITDA_LOW = 1.00
RISK_NET_DEBT_EBITDA_HIGH = 4.00
RISK_INTEREST_COVERAGE_LOW = 1.50
RISK_INTEREST_COVERAGE_HIGH = 6.00
RISK_CURRENT_RATIO_LOW = 1.00
RISK_CURRENT_RATIO_HIGH = 2.00
RISK_QUICK_RATIO_LOW = 0.70
RISK_QUICK_RATIO_HIGH = 1.50

RISK_FCF_VOLATILITY_LOW = 0.25
RISK_FCF_VOLATILITY_HIGH = 1.00
RISK_REVENUE_VOLATILITY_LOW = 0.10
RISK_REVENUE_VOLATILITY_HIGH = 0.30
RISK_MARGIN_VOLATILITY_LOW = 0.05
RISK_MARGIN_VOLATILITY_HIGH = 0.20

RISK_SCORE_WEIGHTS = {
	"market": 0.25,
	"downside": 0.20,
	"drawdown": 0.15,
	"leverage": 0.20,
	"stability": 0.10,
	"valuation": 0.10,
}

RISK_DCF_DISCOUNT_GRID = [0.07, 0.09, 0.11, 0.13]
RISK_DCF_TERMINAL_GROWTH_GRID = [0.01, 0.02, 0.03, 0.04]
